language: node_js
node_js:
  - "8"
stages:
  - name: test
jobs:
  include:
    # Run tests with coverage
    - stage: test
      script: npm test
notifications:
  email:
    on_success: never
    on_failure: change
